name: Run Tests and Build & Push Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in root (debug)
      run: ls -la

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install httpx

    - name: Run tests with pytest
      run: |
        pytest test/test_api.py --maxfail=1 --disable-warnings -q

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME=jakaria6284/titanic_passenger_survival_prediction
        TAG=latest
        docker build -t $IMAGE_NAME:$TAG .
        docker push $IMAGE_NAME:$TAG
